"""initial schema

Revision ID: c424a6ae6258
Revises:
Create Date: 2026-05-10 04:49:26.183791

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c424a6ae6258"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "certificate_orders",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("domains", sa.JSON(), nullable=False, comment="域名列表"),
        sa.Column("email", sa.String(length=255), nullable=False, comment="联系邮箱"),
        sa.Column(
            "cert_type",
            sa.Enum("SINGLE", "WILDCARD", "MULTI", name="certificatetype"),
            nullable=False,
            comment="证书类型",
        ),
        sa.Column(
            "challenge_type",
            sa.Enum("HTTP_01", "DNS_01", name="challengetype"),
            nullable=False,
            comment="验证方式",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "VALIDATING",
                "ISSUED",
                "FAILED",
                "EXPIRED",
                "RENEWING",
                name="orderstatus",
            ),
            nullable=False,
            comment="订单状态",
        ),
        sa.Column("auto_renew", sa.Boolean(), nullable=True, comment="是否自动续期"),
        sa.Column("acme_order_url", sa.String(length=500), nullable=True, comment="ACME 订单 URL"),
        sa.Column(
            "acme_account_key_encrypted",
            sa.LargeBinary(),
            nullable=True,
            comment="ACME Account Key（加密存储）",
        ),
        sa.Column("not_before", sa.DateTime(), nullable=True, comment="证书生效时间"),
        sa.Column("not_after", sa.DateTime(), nullable=True, comment="证书过期时间"),
        sa.Column("csr_encrypted", sa.LargeBinary(), nullable=True, comment="CSR（加密存储）"),
        sa.Column("error_message", sa.Text(), nullable=True, comment="错误信息"),
        sa.Column("created_at", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "acme_challenges",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False, comment="域名"),
        sa.Column("challenge_type", sa.String(length=20), nullable=False, comment="验证类型"),
        sa.Column("token", sa.String(length=100), nullable=True, comment="HTTP-01 Token"),
        sa.Column(
            "key_authorization", sa.Text(), nullable=True, comment="Key Authorization（加密存储）"
        ),
        sa.Column("dns_txt_name", sa.String(length=255), nullable=True, comment="DNS TXT 记录名称"),
        sa.Column("dns_txt_value", sa.Text(), nullable=True, comment="DNS TXT 记录值（加密存储）"),
        sa.Column(
            "status",
            sa.Enum("PENDING", "VALID", "INVALID", name="challengestatus"),
            nullable=False,
            comment="验证状态",
        ),
        sa.Column("validated_at", sa.DateTime(), nullable=True, comment="验证时间"),
        sa.Column("created_at", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["certificate_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "certificate_files",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column(
            "cert_pem_encrypted", sa.LargeBinary(), nullable=True, comment="证书 PEM（加密）"
        ),
        sa.Column(
            "fullchain_pem_encrypted", sa.LargeBinary(), nullable=True, comment="证书链 PEM（加密）"
        ),
        sa.Column(
            "privkey_pem_encrypted",
            sa.LargeBinary(),
            nullable=True,
            comment="私钥 PEM（加密存储，安全重点）",
        ),
        sa.Column(
            "chain_pem_encrypted", sa.LargeBinary(), nullable=True, comment="中间证书 PEM（加密）"
        ),
        sa.Column("serial_number", sa.String(length=100), nullable=True, comment="证书序列号"),
        sa.Column("fingerprint", sa.String(length=100), nullable=True, comment="证书指纹"),
        sa.Column("created_at", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["certificate_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id"),
    )
    op.create_table(
        "deployment_targets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "WEBHOOK",
                "SSH",
                "LOCAL_PATH",
                "OBJECT_STORAGE",
                "MANUAL_DOWNLOAD",
                name="deploymenttype",
            ),
            nullable=False,
            comment="部署类型",
        ),
        sa.Column("name", sa.String(length=100), nullable=False, comment="部署名称"),
        sa.Column("config_json", sa.JSON(), nullable=False, comment="配置详情"),
        sa.Column("enabled", sa.Boolean(), nullable=True, comment="是否启用"),
        sa.Column("created_at", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["certificate_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("deployment_targets")
    op.drop_table("certificate_files")
    op.drop_table("acme_challenges")
    op.drop_table("certificate_orders")
    # ### end Alembic commands ###
